---
output:
  tufte::tufte_handout
link-citations: yes
---

```{r setup, include=FALSE, results="hide", warning=FALSE}
library(ggplot2)
library(data.table)

knitr::opts_chunk$set(echo = FALSE,
                      fig.width = 4.21,
                      fig.height = 4.21)

starLogs <- readRDS("../output/mappingStats/starLogs.Rds")
starLogs[, Accession := substr(Library, 1, 1)]
starLogs[, Accession := plyr::mapvalues(Accession, from = c("J", "I", "R", "G", "B"),
                           to = c("Os Japonica", "Os Indica", "Or", "Og", "Ob"))]
```

# Quality checks

```{r readsInGenes, fig.cap="Number of input reads \\emph{vs}. number of reads mapped to genes"}
ggplot(starLogs, aes(x = `Number of input reads`/1000000,
                          y = `Number of reads in genes`/1000000,
                          label = Library, colour = Accession)) +
  xlab("Input reads (M)") +
  ylab("Exonic mappings (M)") +
  theme_grey(base_size = 8) +
  theme(legend.position = "bottom") +
  stat_smooth(method = "lm", se = FALSE, size = 0.5) +
  geom_point() +
  scale_colour_brewer(palette = "Set1", guide = guide_legend(title = NULL)) +
  geom_text(aes(x = (`Number of input reads`/1000000) - 2),
            check_overlap = TRUE, size = 2.82)
ggsave(filename = "exonic_mapping.pdf",
       device = cairo_pdf(),
       width = 10,
       height = 7.5,
       units = "in")
```


```{r uniqueMulti, fig.cap="Uniquely mapped reads by accession"}
ggplot(starLogs, aes(y = `Uniquely mapped reads %`,
                          x = Accession,
                          label = Library, colour = Accession)) +
  ylab("Uniquely mapped reads (%)") +
  #xlab("Reads mapped to multiple loci (%)") +
  theme_grey(base_size = 8) +
  theme(legend.position = "bottom") +
  #stat_smooth(method = "lm", se = FALSE, size = 0.5) +
  geom_point(alpha = 0.8, position = position_jitter(width = 0.3)) +
  scale_colour_brewer(palette = "Set1", guide = guide_legend(title = NULL))
#  geom_text(aes(x = (`Number of input reads`/1000000) - 2),
            #check_overlap = TRUE, size = 2.82)
ggsave(filename = "reads_per_accession.pdf",
       device = cairo_pdf(),
       width = 10,
       height = 7.5,
       units = "in")
```

```{r facetPercents, fig.fullwidth = TRUE, fig.width = 6.48, fig.height = 4.21}
mapping.percentages.wide <- starLogs[, .(Library, Accession, `Uniquely mapped reads %`,
             `% of reads unmapped: too short`,
             `% of reads mapped to multiple loci`,
             `% of reads mapped to too many loci`)]
mapping.percentages <- reshape2::melt(mapping.percentages.wide,
                                      id.vars = c("Library", "Accession"))
ggplot(mapping.percentages, aes(x = factor(Accession,
                                           levels = c("Os Japonica", "Os Indica",
                                                      "Or", "Og", "Ob")),
                                y = value, colour = Accession)) +
  xlab(NULL) + ylab("Percentage") +
  facet_wrap(~variable, scales = "free_y") +
  geom_point(alpha = 0.8, position = position_jitter(width = 0.3)) +
  scale_colour_brewer(palette = "Set1", guide = FALSE)
ggsave(filename = "mapping_percentages.pdf",
       device = cairo_pdf(),
       width = 10,
       height = 7.5,
       units = "in")

```